BINARY     := dva
MODULE     := github.com/ScriptonBasestar/dva
BUILD_DIR  := ./bin
GOFLAGS     := -trimpath
LIBRARY_DIR  := ai-docs/workflow/setup-dva/library
WORKFLOW_DIR := ai-docs/workflow/setup-dva
GENERATED    := internal/cli/library_reference.txt
GENERATED_WF := internal/cli/setup_dva_workflow.txt

.PHONY: build install test test-integration lint clean fmt vet help bump-version generate check-generate

## build: Build the dva binary
build: generate generate-workflow
	$(eval VERSION := $(shell grep 'Version =' internal/config/version.go | cut -d'"' -f2))
	$(eval COMMIT  := $(shell git rev-parse --short HEAD 2>/dev/null || echo "none"))
	$(eval BUILD_DATE := $(shell date +%Y-%m-%dT%H:%M:%S))
	go build $(GOFLAGS) -ldflags '-s -w -X $(MODULE)/internal/config.Version=$(VERSION) -X $(MODULE)/internal/config.Commit=$(COMMIT) -X $(MODULE)/internal/config.BuildDate=$(BUILD_DATE)' -o $(BUILD_DIR)/$(BINARY) ./cmd/dva

## bump-version: Bump micro version if there are changes or new commit
bump-version:
	@LAST_COMMIT=$$(cat .last_built_commit 2>/dev/null || echo ""); \
	CURRENT_COMMIT=$$(git rev-parse HEAD 2>/dev/null || echo "none"); \
	DIRTY=$$(git status --porcelain | grep -v 'internal/config/version.go'); \
	if [ "$$CURRENT_COMMIT" != "$$LAST_COMMIT" ] || [ -n "$$DIRTY" ]; then \
		echo "Changes or new commit detected, bumping version..."; \
		CURRENT_VERSION=$$(grep 'Version =' internal/config/version.go | cut -d'"' -f2); \
		MAJOR=$$(echo $$CURRENT_VERSION | cut -d. -f1); \
		MINOR=$$(echo $$CURRENT_VERSION | cut -d. -f2); \
		PATCH=$$(echo $$CURRENT_VERSION | cut -d. -f3); \
		NEW_PATCH=$$(($$PATCH + 1)); \
		NEW_VERSION="$$MAJOR.$$MINOR.$$NEW_PATCH"; \
		sed -i.bak "s/Version = \"$$CURRENT_VERSION\"/Version = \"$$NEW_VERSION\"/" internal/config/version.go && rm -f internal/config/version.go.bak; \
		echo "$$CURRENT_COMMIT" > .last_built_commit; \
		echo "Version bumped to $$NEW_VERSION"; \
	fi

## install: Install dva to ~/.local/bin (bumps version if changes detected)
install: bump-version build
	@mkdir -p $(HOME)/.local/bin
	cp $(BUILD_DIR)/$(BINARY) $(HOME)/.local/bin/$(BINARY)
	@GOBIN=$$(go env GOBIN); [ -n "$$GOBIN" ] && cp $(BUILD_DIR)/$(BINARY) "$$GOBIN/$(BINARY)" || true

## test: Run all tests
test:
	go test -race -cover ./...

## test-integration: Run integration tests (requires build tag)
test-integration:
	go test -tags=integration -race ./internal/integration/...

## lint: Run linters
lint: vet
	@which golangci-lint > /dev/null 2>&1 || echo "Install golangci-lint: https://golangci-lint.run/usage/install/"
	golangci-lint run ./...

## vet: Run go vet
vet:
	go vet ./...

## fmt: Format code
fmt:
	gofmt -w -s .

## clean: Remove build artifacts
clean:
	rm -rf $(BUILD_DIR)
	go clean -cache

## generate: Concatenate library files into embeddable reference
generate:
	@{ echo "# DO NOT EDIT — generated by 'make generate' from $(LIBRARY_DIR)/"; \
	   echo "# Source: dva-schema.md, naming-presets.md, reference-examples.md"; \
	   echo ""; \
	   cat $(LIBRARY_DIR)/dva-schema.md; \
	   echo ""; \
	   cat $(LIBRARY_DIR)/naming-presets.md; \
	   echo ""; \
	   cat $(LIBRARY_DIR)/reference-examples.md; \
	} > $(GENERATED)

## generate-workflow: Bundle setup-dva workflow files into embeddable reference
generate-workflow:
	@{ echo "# DO NOT EDIT — generated by 'make generate-workflow' from $(WORKFLOW_DIR)/"; \
	   echo ""; \
	   for f in auto.md \
	            stages/00-analyze.md stages/10-verify.md stages/20-transform.md \
	            stages/30-configure-full.md stages/30-configure-adopt.md \
	            stages/40-execute.md verify/checklist.md; do \
	     echo "--- FILE: $$f ---"; \
	     cat $(WORKFLOW_DIR)/$$f; \
	     echo ""; \
	   done; \
	} > $(GENERATED_WF)

## check-generate: Verify generated files are up-to-date (CI)
check-generate: generate generate-workflow
	@git diff --exit-code $(GENERATED) $(GENERATED_WF) || { echo "ERROR: generated files are stale — run 'make generate' and commit"; exit 1; }

## help: Show this help
help:
	@echo "Available targets:"
	@grep -E '^##' $(MAKEFILE_LIST) | sed 's/## /  /' | column -t -s ':'
