BINARY     := dva
MODULE     := github.com/ScriptonBasestar/dva
BUILD_DIR  := ./bin
GOFLAGS     := -trimpath

# Workflow source directories (single source of truth)
WF_LIBRARY  := workflow/library
WF_AUTO     := workflow/improve/auto
WF_GUIDED   := workflow/improve/guided
WF_DIAGNOSE := workflow/improve/diagnose

# Generated embeddable files (output of make generate)
GEN_DIR         := internal/cli
GEN_LIBRARY     := $(GEN_DIR)/library_reference.txt
GEN_WORKFLOW    := $(GEN_DIR)/improve_guided_workflow.txt
GEN_PROMPT      := $(GEN_DIR)/improve_prompt_template.txt
GEN_GUARD_DEF   := $(GEN_DIR)/improve_guardrails_default.txt
GEN_GUARD_RW    := $(GEN_DIR)/improve_guardrails_rewrite.txt
GEN_DIAGNOSE    := $(GEN_DIR)/diagnose_prompt_template.txt

.PHONY: build install test test-integration lint clean fmt vet help generate check-generate

## build: Build the dva binary
build: generate
	$(eval VERSION := $(shell grep 'Version =' internal/config/version.go | cut -d'"' -f2))
	$(eval COMMIT  := $(shell git rev-parse --short HEAD 2>/dev/null || echo "none"))
	$(eval BUILD_DATE := $(shell date +%Y-%m-%dT%H:%M:%S))
	go build $(GOFLAGS) -ldflags '-s -w -X $(MODULE)/internal/config.Version=$(VERSION) -X $(MODULE)/internal/config.Commit=$(COMMIT) -X $(MODULE)/internal/config.BuildDate=$(BUILD_DATE)' -o $(BUILD_DIR)/$(BINARY) ./cmd/dva

## install: Install dva to ~/.local/bin
install: build
	@mkdir -p $(HOME)/.local/bin
	rm -f $(HOME)/.local/bin/$(BINARY)
	cp $(BUILD_DIR)/$(BINARY) $(HOME)/.local/bin/$(BINARY)
	@GOBIN=$$(go env GOBIN); [ -n "$$GOBIN" ] && { rm -f "$$GOBIN/$(BINARY)"; cp $(BUILD_DIR)/$(BINARY) "$$GOBIN/$(BINARY)"; } || true

## test: Run all tests
test:
	go test -race -cover ./...

## test-integration: Run integration tests (requires build tag)
test-integration:
	go test -tags=integration -race ./internal/integration/...

## lint: Run linters
lint: vet
	@which golangci-lint > /dev/null 2>&1 || echo "Install golangci-lint: https://golangci-lint.run/usage/install/"
	golangci-lint run ./...

## vet: Run go vet
vet:
	go vet ./...

## fmt: Format code
fmt:
	gofmt -w -s .

## clean: Remove build artifacts
clean:
	rm -rf $(BUILD_DIR)
	go clean -cache

## generate: Generate all embeddable files from workflow/ source
generate:
	@echo "Generating embeddable files from workflow/..."
	@# Library reference: shared rules + schema + presets + examples
	@{ echo "# DO NOT EDIT — generated by 'make generate' from $(WF_LIBRARY)/"; \
	   echo ""; \
	   cat $(WF_LIBRARY)/shared-guardrails.md; \
	   echo ""; \
	   cat $(WF_LIBRARY)/shared-checklist.md; \
	   echo ""; \
	   cat $(WF_LIBRARY)/dva-schema.md; \
	   echo ""; \
	   cat $(WF_LIBRARY)/naming-presets.md; \
	   echo ""; \
	   cat $(WF_LIBRARY)/reference-examples.md; \
	} > $(GEN_LIBRARY)
	@# Guided improve workflow bundle
	@{ echo "# DO NOT EDIT — generated by 'make generate' from $(WF_GUIDED)/"; \
	   echo ""; \
	   for f in orchestrator.md \
	            stages/00-analyze.md stages/10-verify.md stages/20-transform.md \
	            stages/30-configure-full.md stages/30-configure-adopt.md \
	            stages/40-execute.md verify/checklist.md; do \
	     echo "--- FILE: $$f ---"; \
	     cat $(WF_GUIDED)/$$f; \
	     echo ""; \
	   done; \
	} > $(GEN_WORKFLOW)
	@# Auto improve prompts: copy from workflow source
	@cp $(WF_AUTO)/prompt-template.md $(GEN_PROMPT)
	@cp $(WF_AUTO)/guardrails-default.md $(GEN_GUARD_DEF)
	@cp $(WF_AUTO)/guardrails-rewrite.md $(GEN_GUARD_RW)
	@# Diagnose prompt template
	@cp $(WF_DIAGNOSE)/prompt-template.md $(GEN_DIAGNOSE)
	@echo "Generated: $(GEN_LIBRARY) $(GEN_WORKFLOW) $(GEN_PROMPT) $(GEN_GUARD_DEF) $(GEN_GUARD_RW) $(GEN_DIAGNOSE)"

## check-generate: Verify generated files are up-to-date (CI)
check-generate: generate
	@git diff --exit-code $(GEN_LIBRARY) $(GEN_WORKFLOW) $(GEN_PROMPT) $(GEN_GUARD_DEF) $(GEN_GUARD_RW) $(GEN_DIAGNOSE) \
		|| { echo "ERROR: generated files are stale — run 'make generate' and commit"; exit 1; }

## help: Show this help
help:
	@echo "Available targets:"
	@grep -E '^##' $(MAKEFILE_LIST) | sed 's/## /  /' | column -t -s ':'
