package cli

import (
	"fmt"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/ScriptonBasestar/dva/internal/config"
)

var migrateCmd = &cobra.Command{
	Use:   "migrate",
	Short: "Generate LLM-friendly migration guide for dva.yml version upgrades",
	RunE: func(cmd *cobra.Command, args []string) error {
		c := mustLoadConfig()

		currentVersion := c.Version
		if currentVersion == "" {
			currentVersion = "unknown"
		}

		targetVersion := config.Version
		if !needsMigration(currentVersion, targetVersion) {
			fmt.Printf("✅ Your dva.yml is already at version %s\n", currentVersion)
			return nil
		}

		fmt.Println(buildMigrationPrompt(c, currentVersion, targetVersion))
		return nil
	},
}

func needsMigration(current, target string) bool {
	if current == "unknown" {
		return true
	}
	return current != target
}

func buildMigrationPrompt(c *config.Config, currentVersion, targetVersion string) string {
	var out []string

	out = append(out, "# Hip Configuration Migration Guide\n")
	out = append(out, "## Current Configuration")
	out = append(out, fmt.Sprintf("- **File**: %s", c.FilePath()))
	out = append(out, fmt.Sprintf("- **Current Version**: %s", currentVersion))
	out = append(out, fmt.Sprintf("- **Latest Version**: %s", config.Version))
	out = append(out, "- **Migration Required**: YES\n")
	out = append(out, "---\n")

	// Detect deprecated features
	var issues []string
	for name, cmd := range c.Interaction {
		if len(cmd.ComposeRunOptions) > 0 {
			issues = append(issues, fmt.Sprintf(
				"### compose_run_options (Deprecated)\n"+
					"**Location**: `interaction.%s`\n"+
					"**Migrate to**: `compose.run_options`\n", name))
		}
	}

	if len(issues) > 0 {
		out = append(out, "## Breaking Changes & Deprecations\n")
		out = append(out, issues...)
		out = append(out, "---\n")
	}

	// New features
	out = append(out, "## New Features Available\n")
	out = append(out, "### env_file Support")
	out = append(out, "Load environment variables from .env files:\n")
	out = append(out, "```yaml")
	out = append(out, "env_file: .env")
	out = append(out, "# or multiple files:")
	out = append(out, "env_file:")
	out = append(out, "  - .env.defaults")
	out = append(out, "  - .env.local")
	out = append(out, "```\n")
	out = append(out, "---\n")

	// Validation
	out = append(out, "## Validation\n")
	if err := c.Validate(); err == nil {
		out = append(out, "✅ Your current configuration is valid.\n")
	} else {
		out = append(out, fmt.Sprintf("❌ Validation failed: %s\n", err))
	}
	out = append(out, "---\n")

	// Checklist
	out = append(out, "## Migration Checklist\n")
	out = append(out, fmt.Sprintf("- [ ] Update `version: '%s'` → `version: '%s'`", currentVersion, targetVersion))
	out = append(out, "- [ ] Run `dva validate` to verify changes")
	out = append(out, "- [ ] Test provision: `dva provision`\n")
	out = append(out, "---\n")

	out = append(out, fmt.Sprintf("**Generated by**: dva v%s", config.Version))
	out = append(out, fmt.Sprintf("**Date**: %s", time.Now().Format("2006-01-02")))

	return strings.Join(out, "\n")
}
