package skillinstall

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	pathpkg "path"
	"sort"
	"strings"

	bundled "github.com/ScriptonBasestar/dva/skills"
)

// agentMeshBundle compiles the portable Agent Skills bundle to Agent Mesh's
// flat Markdown format. References are inlined because Agent Mesh's handling
// of a sibling reference bundle is not part of this install contract.
func agentMeshBundle() (skillBundle, error) {
	bundle := skillBundle{contents: make(map[string][]byte, len(bundled.Names))}
	for _, name := range bundled.Names {
		contents, err := renderAgentMeshSkill(name)
		if err != nil {
			return skillBundle{}, err
		}
		path := name + ".md"
		digest := sha256.Sum256(contents)
		bundle.files = append(bundle.files, fileHash{Path: path, SHA: hex.EncodeToString(digest[:])})
		bundle.contents[path] = contents
	}
	sort.Slice(bundle.files, func(i, j int) bool { return bundle.files[i].Path < bundle.files[j].Path })
	return bundle, nil
}

func renderAgentMeshSkill(name string) ([]byte, error) {
	skillPath := pathpkg.Join(name, "SKILL.md")
	skill, err := bundled.Files.ReadFile(skillPath)
	if err != nil {
		return nil, err
	}
	body, err := stripFrontmatter(string(skill))
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", skillPath, err)
	}
	body = rewriteRelativeReferenceLinks(name, body)
	var output strings.Builder
	output.WriteString("<!-- Generated by `dva skill install --runtime agent-mesh`; do not edit.\n")
	output.WriteString("Source version and bundle SHA-256 are recorded by `dva skill status`.\n")
	output.WriteString("Canonical source: https://github.com/ScriptonBasestar/dva/tree/master/skills/")
	output.WriteString(name)
	output.WriteString(". Relative reference documents are inlined below because Agent Mesh reference-bundle resolution is not assumed. -->\n\n")
	output.WriteString(strings.TrimSpace(body))

	references, err := fs.ReadDir(bundled.Files, pathpkg.Join(name, "references"))
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return []byte(output.String() + "\n"), nil
		}
		return nil, err
	}
	for _, reference := range references {
		if reference.IsDir() || !strings.HasSuffix(reference.Name(), ".md") {
			continue
		}
		referencePath := pathpkg.Join(name, "references", reference.Name())
		contents, err := bundled.Files.ReadFile(referencePath)
		if err != nil {
			return nil, err
		}
		output.WriteString("\n\n## Reference: ")
		output.WriteString(reference.Name())
		output.WriteString("\n\n")
		output.WriteString(strings.TrimSpace(rewriteRelativeReferenceLinks(name, string(contents))))
	}
	return []byte(output.String() + "\n"), nil
}

func stripFrontmatter(source string) (string, error) {
	if !strings.HasPrefix(source, "---\n") {
		return source, nil
	}
	end := strings.Index(source[len("---\n"):], "\n---\n")
	if end < 0 {
		return "", fmt.Errorf("unterminated YAML frontmatter")
	}
	return source[len("---\n")+end+len("\n---\n"):], nil
}

func rewriteRelativeReferenceLinks(skill, source string) string {
	entries, err := fs.ReadDir(bundled.Files, pathpkg.Join(skill, "references"))
	if err != nil {
		return source
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		relative := "references/" + entry.Name()
		canonical := "https://github.com/ScriptonBasestar/dva/blob/master/skills/" + skill + "/" + relative
		source = strings.ReplaceAll(source, "]("+relative+")", "]("+canonical+")")
		source = strings.ReplaceAll(source, "]("+relative+"#", "]("+canonical+"#")
	}
	return source
}
