package skillinstall

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	pathpkg "path"
	"sort"
	"strings"

	bundled "github.com/ScriptonBasestar/dva/skills"
)

// agentMeshBundle compiles the portable Agent Skills bundle to Agent Mesh's
// flat Markdown format. References are inlined because Agent Mesh's handling
// of a sibling reference bundle is not part of this install contract.
func agentMeshBundle() (skillBundle, error) {
	bundle := skillBundle{contents: make(map[string][]byte, len(bundled.Names))}
	for _, name := range bundled.Names {
		contents, err := renderAgentMeshSkill(name)
		if err != nil {
			return skillBundle{}, err
		}
		path := name + ".md"
		digest := sha256.Sum256(contents)
		bundle.files = append(bundle.files, fileHash{Path: path, SHA: hex.EncodeToString(digest[:])})
		bundle.contents[path] = contents
	}
	sort.Slice(bundle.files, func(i, j int) bool { return bundle.files[i].Path < bundle.files[j].Path })
	return bundle, nil
}

func renderAgentMeshSkill(name string) ([]byte, error) {
	skillPath := pathpkg.Join(name, "SKILL.md")
	skill, err := bundled.Files.ReadFile(skillPath)
	if err != nil {
		return nil, err
	}
	body, err := stripFrontmatter(string(skill))
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", skillPath, err)
	}
	body = rewriteLocalSkillPaths(name, body)
	var output strings.Builder
	output.WriteString("<!-- Generated by `dva skill install --runtime agent-mesh`; do not edit.\n")
	output.WriteString("Source version and bundle SHA-256 are recorded by `dva skill status`.\n")
	output.WriteString("Canonical source: https://github.com/ScriptonBasestar/dva/tree/master/skills/")
	output.WriteString(name)
	output.WriteString(". Relative reference documents are inlined below because Agent Mesh reference-bundle resolution is not assumed. -->\n\n")
	output.WriteString(strings.TrimSpace(body))
	output.WriteString(localResourceIndex(name))

	for _, source := range []struct {
		kind, directory string
	}{
		{kind: "Reference", directory: "references"},
		{kind: "Asset", directory: "assets"},
	} {
		paths, err := bundledTextPaths(name, source.directory)
		if err != nil {
			return nil, err
		}
		for _, relative := range paths {
			contents, err := bundled.Files.ReadFile(pathpkg.Join(name, relative))
			if err != nil {
				return nil, err
			}
			output.WriteString("\n\n<a id=\"")
			output.WriteString(inlineAnchor(name, relative))
			output.WriteString("\"></a>\n\n## ")
			output.WriteString(source.kind)
			output.WriteString(": ")
			output.WriteString(relative)
			output.WriteString("\n\n")
			if source.kind == "Asset" {
				output.WriteString("```")
				output.WriteString(assetLanguage(relative))
				output.WriteString("\n")
				output.WriteString(strings.TrimSpace(string(contents)))
				output.WriteString("\n```")
			} else {
				output.WriteString(strings.TrimSpace(demoteHeadings(rewriteLocalSkillPaths(name, string(contents)), 2)))
			}
		}
	}
	return []byte(output.String() + "\n"), nil
}

func stripFrontmatter(source string) (string, error) {
	if !strings.HasPrefix(source, "---\n") {
		return source, nil
	}
	end := strings.Index(source[len("---\n"):], "\n---\n")
	if end < 0 {
		return "", fmt.Errorf("unterminated YAML frontmatter")
	}
	return source[len("---\n")+end+len("\n---\n"):], nil
}

func bundledTextPaths(skill, directory string) ([]string, error) {
	var paths []string
	err := fs.WalkDir(bundled.Files, pathpkg.Join(skill, directory), func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				return nil
			}
			return err
		}
		if !entry.IsDir() {
			paths = append(paths, strings.TrimPrefix(path, skill+"/"))
		}
		return nil
	})
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	sort.Strings(paths)
	return paths, err
}

func rewriteLocalSkillPaths(skill, source string) string {
	resources := localResources(skill)
	fenced := false
	var output strings.Builder
	for _, line := range strings.SplitAfter(source, "\n") {
		trimmed := strings.TrimLeft(line, " \t")
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			fenced = !fenced
			output.WriteString(line)
			continue
		}
		if fenced {
			output.WriteString(line)
			continue
		}
		parts := strings.Split(line, "`")
		for index := 0; index < len(parts); index += 2 {
			parts[index] = rewriteProsePaths(parts[index], resources)
		}
		output.WriteString(strings.Join(parts, "`"))
	}
	return output.String()
}

type localResource struct{ path, target string }

func localResources(skill string) []localResource {
	var resources []localResource
	for _, directory := range []string{"references", "assets"} {
		paths, err := bundledTextPaths(skill, directory)
		if err != nil {
			continue
		}
		for _, relative := range paths {
			resources = append(resources, localResource{relative, "#" + inlineAnchor(skill, relative)})
		}
	}
	// Cross-skill references are not inlined into a different flat skill. Keep
	// them as explicit canonical links rather than assuming a sibling bundle.
	for _, other := range bundled.Names {
		if other == skill {
			continue
		}
		paths, err := bundledTextPaths(other, "references")
		if err != nil {
			continue
		}
		for _, relative := range paths {
			resources = append(resources, localResource{"skills/" + other + "/" + relative, "https://github.com/ScriptonBasestar/dva/blob/master/skills/" + other + "/" + relative})
		}
	}
	return resources
}

func rewriteProsePaths(source string, resources []localResource) string {
	for _, resource := range resources {
		source = strings.ReplaceAll(source, "]("+resource.path+")", "]("+resource.target+")")
		source = strings.ReplaceAll(source, "]("+resource.path+"#", "]("+resource.target+"#")
		source = strings.ReplaceAll(source, resource.path, "[inline "+resource.path+"]("+resource.target+")")
	}
	return source
}

func localResourceIndex(skill string) string {
	resources := localResources(skill)
	if len(resources) == 0 {
		return ""
	}
	var output strings.Builder
	output.WriteString("\n\n## Local resource index\n")
	for _, resource := range resources {
		output.WriteString("\n- [")
		output.WriteString(resource.path)
		output.WriteString("](")
		output.WriteString(resource.target)
		output.WriteString(")")
	}
	return output.String()
}

func inlineAnchor(skill, relative string) string {
	replacer := strings.NewReplacer("/", "-", ".", "-", "_", "-")
	return "dva-" + replacer.Replace(skill+"-"+relative)
}

func demoteHeadings(source string, levels int) string {
	var output strings.Builder
	fenced := false
	for _, line := range strings.Split(source, "\n") {
		trimmed := strings.TrimLeft(line, " \t")
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			fenced = !fenced
		}
		if !fenced && strings.HasPrefix(line, "#") {
			count := len(line) - len(strings.TrimLeft(line, "#"))
			if count > 0 && count < 7 && len(line) > count && line[count] == ' ' {
				line = strings.Repeat("#", levels) + line
			}
		}
		output.WriteString(line)
		output.WriteByte('\n')
	}
	return strings.TrimSuffix(output.String(), "\n")
}

func assetLanguage(path string) string {
	if strings.HasSuffix(path, ".yml") || strings.HasSuffix(path, ".yaml") {
		return "yaml"
	}
	return "text"
}
